version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ../backend:/var/www/backend
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=focoweb
      - DB_USERNAME=root
      - DB_PASSWORD=Acces@@LibreN@Gratuit@@!!

  frontend:
    build:
      context: ..
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ../frontend:/usr/src/frontend
    ports:
      - "3000:3000"

  db:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Acces@@LibreN@Gratuit@@!!
      MYSQL_DATABASE: focoweb
      MYSQL_USER: root
      MYSQL_PASSWORD: Acces@@LibreN@Gratuit@@!!
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
